### ISSUE TITLE
Consume new error/problem payload

### ISSUE THREAD

**Issue by pturczyk** [zalando/pazuzu-ui#59]
This is the UI counterpart issue for zalando/pazuzu-registry#41.

A new error payload structure has been implemented in pazuzu-registry in accordance to application/problem+json which now needs to be properly consumed by the UI. Example payload:

```json
{
   "type" : "http://pazuzu.io/error/fency_exception",
   "title" : "This is a fency exception", 
   "status" : 400,
   "detail": "Request was not fency enough to be fulfilled"
}
```
The mapping from the previous structure looks like following:

- "code" is now returned as part of the "type" URL
- "message" is now returned as "title"
- "detailed_message" is now returned as "detail"

**Comment by truemped** [comment]
Resolved in #60
